query($showId: Int, $page: Int) {
    Media(id: $showId) {
        title {
            romaji
        },
        episodes,
        nextAiringEpisode {
            timeUntilAiring
        },
        duration,
        characters(sort: ROLE, page: $page, perPage: 100) {
            pageInfo {
                currentPage,
                hasNextPage
            },
            nodes {
                id,
                image {
                    medium,
                    large
                },
                name {
                    first,
                    middle,
                    last,
                    full,
                    native
                },
                siteUrl,
            }
        }
    }
}
